apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pedidos-prod
resources:
  - namespace.yaml
  - ../../base
  - ingress.yaml
images:
  - name: pedidos
    newName: meuregistro.azurecr.io/pedidos
    newTag: "1.0"
patches:
  - path: recursos-prod.yaml
